#数据源连接信息
spring:
  datasource:
    username: root
    password: LCYssb123456
    url: jdbc:mysql://106.55.255.162:3306/jira?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

